clone:
    path: github.com/vmware/docker-volume-vsphere
    tags: true

build:
  build_dev:
    image: cnastorage/vibauthor-and-go:0.6
    commands:
      - go get github.com/golang/lint/golint
      - make build
    when:
      event: [push, pull_request]

  package:
    image: cnastorage/fpm
    commands:
      - make deb rpm

  test:
    image: cnastorage/vibauthor-and-go:0.6
    privileged: true
    environment:
    commands:
      - ./misc/drone-scripts/deploy-and-test-wrapper.sh $$ESX $$VM1 $$VM2 $$BUILD_NUMBER $$IS_VSAN_TEST < /dev/null

matrix:
  GO_VERSION:
    - 1.6
